### ISSUE TITLE
Undefined names in elevator.py

### ISSUE THREAD

**Issue by cclauss** [jayshah19949596/CodingInterviews#6]
[flake8](http://flake8.pycqa.org) testing of https://github.com/jayshah19949596/CodingInterviews on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./VISA Senior Software Engineer 2019/Round - 3 - Onsite/Design Elevator/elevator.py:5:20: F821 undefined name 'dequeu'
        self.req = dequeu([])
                   ^
./VISA Senior Software Engineer 2019/Round - 3 - Onsite/Design Elevator/elevator.py:20:32: F821 undefined name 'cf'
            self.get_direction(cf, gf)
                               ^
./VISA Senior Software Engineer 2019/Round - 3 - Onsite/Design Elevator/elevator.py:20:36: F821 undefined name 'gf'
            self.get_direction(cf, gf)
                                   ^
./VISA Senior Software Engineer 2019/Round - 3 - Onsite/Design Elevator/elevator.py:21:29: F821 undefined name 'cf'
            self.go_to_dest(cf, goal_floor)
                            ^
./VISA Senior Software Engineer 2019/Round - 3 - Onsite/Design Elevator/elevator.py:24:17: F821 undefined name 'goal_floor'
        if cf > goal_floor:
                ^
5     F821 undefined name 'dequeu'
5
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by jayshah19949596** [comment]
I have made a new commit and I have solved the issues... I will close the issue
